import { Montserrat } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import "./globals.css";
import Header from "./_components/Header";
import Footer from './_components/Footer';

const raleway = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={raleway.className}>
        <div className='md:px-20'>
          <Header />
          {children}
          <Toaster/>
        </div>
        <Footer />
      </body>
    </html>
  )
}
